### ISSUE TITLE
A bug when running the demo

### ISSUE THREAD

**Issue by Pythongorean** [rmgarnett/active_gp_hyperlearning#1]
Hi! I got a bug in the line 51 when I run the demo. Specifically, the K is not positive semi-definite. Then I went back to decompose K, finding a lot of negative eigenvalues with very small absolute value(e-10 scale). So I substituted those negative small eigenvalues with 0 and reconstructed the K matrix. Then the mvnrnd could work. Did you have this bug when you run the demo? I'm not sure whether there is a bug in demo code or I've made a mistake. Thanks!

**Comment by rmgarnett** [comment]
Fixed! Numerical issues caused K to be slightly asymmetric.
