### ISSUE TITLE
demo script error

### ISSUE THREAD

**Issue by dieloz** [rmgarnett/active_gp_hyperlearning#3]
Dear Roman,
I read your paper (https://arxiv.org/pdf/1310.6740.pdf) on active learning using GP and found your matlab implementation here. Unfortunately, I run the demo script of your learn_gp_hyperparameters.m function and I got this error (see below). It seems that using the @constant_mean function it's not possible to get 2 outputs. 
In anticipation, sorry in case I missed something and thank you very much for making your releasing your code
Diego

% actively learn GP hyperparameters
results = learn_gp_hyperparameters(problem, model);
Error using constant_mean
Too many output arguments.

Error in infGaussLik (line 23)
[m,dm] = feval(mean{:}, hyp.mean, x);           % evaluate mean vector and deriv

Error in infExact (line 6)
varargout = cell(nargout, 1); [varargout{:}] = infGaussLik(varargin{:});

Error in exact_inference (line 79)
        infExact(theta, mean_function, covariance_function, 'likGauss', x, y);

Error in inference_with_prior (line 100)
        inference_method(theta, mean_function, covariance_function, ...

Error in
add_prior_to_inference_method>@(hyperparameters,mean_function,covariance_function,likelihood,x,y)inference_with_prior(inference_method,prior,hyperparameters,mean_function,covariance_function,likelihood,x,y)
(line 37)
      inference_with_prior(inference_method, prior, hyperparameters, ...

Error in inference_with_prior (line 100)
        inference_method(theta, mean_function, covariance_function, ...

Error in
add_prior_to_inference_method>@(hyperparameters,mean_function,covariance_function,likelihood,x,y)inference_with_prior(inference_method,prior,hyperparameters,mean_function,covariance_function,likelihood,x,y)
(line 37)
      inference_with_prior(inference_method, prior, hyperparameters, ...

Error in
gp_optimizer_wrapper>@()(feval(inference_method{:},theta,mean_function,covariance_function,likelihood,x,y))
(line 87)
  f = @() (feval(inference_method{:}, theta, mean_function, ...

Error in gp_optimizer_wrapper (line 95)
    [~, nlZ, dnlZ] = f();

Error in
minimize_minFunc>@(hyperparameter_values)gp_optimizer_wrapper(hyperparameter_values,initial_hyperparameters,model.inference_method,model.mean_function,model.covariance_function,model.likelihood,x,y)
(line 80)
  f = @(hyperparameter_values) gp_optimizer_wrapper(hyperparameter_values, ...

Error in minFunc (line 314)
    [f,g] = funObj(x,varargin{:});

Error in minimize_minFunc (line 86)
      minFunc(f, unwrap(initial_hyperparameters), options.minFunc_options);

Error in learn_gp_hyperparameters (line 184)
        minimize_minFunc(model, x, y, ...

**Comment by rmgarnett** [comment]
The code currently will only work with GPML v3.x.

**Comment by dieloz** [comment]
thank you very much for your prompt reply. I just try with v3.6 and it worked like a charm
